function parameters = compute_parameters(data, dates, discounts,strike,spread)

    spot_price = data.reference;
    dividend   = data.dividends;
    
    % t0 is the swap start date (spot lag = 2bd), not the valuation date
    valuationDate     = datenum(data.date, 'yyyymmdd');
    startDate         = business_date_offset(valuationDate, 'day_offset', 2);
    first_coupon_date = business_date_offset(startDate, 'year_offset', 1, ...
                                             'convention', 'modified_following');
    maturity_date     = business_date_offset(startDate, 'year_offset', 2, ...
                                             'convention', 'modified_following');
    
    % NB: reset is 2bd before each payment date. Using payment dates as a 
    % proxy for resets here -> ~2bd approximation in the digital observation.
    
    B_t1 = get_discount_factor_by_zero_rates_linear_interp(startDate, ...
              first_coupon_date, dates, discounts);
    B_t2 = get_discount_factor_by_zero_rates_linear_interp(startDate, ...
              maturity_date, dates, discounts);
    
    % Act/365 to stay consistent with continuous compounding
    ttm_1 = yearfrac(startDate, first_coupon_date, 3);
    ttm_2 = yearfrac(startDate, maturity_date,     3);
    
    % Curve is not flat -> keep one rate per pillar
    rate_1 = -log(B_t1) / ttm_1;
    rate_2 = -log(B_t2) / ttm_2;
    
    % Forward at t1 drives the digital. No forward at t2 needed: the 2%
    % coupon is deterministic conditional on no early redemption.
    F0_t1 = spot_price * exp((rate_1 - dividend) * ttm_1);
    
    parameters = struct( ...
        'spot',            spot_price,        ...
        'dividend',        dividend,          ...
        'valuationDate',   valuationDate,     ...
        'startDate',       startDate,         ...
        'firstCouponDate', first_coupon_date, ...
        'maturityDate',    maturity_date,     ...
        'B_t1',            B_t1,              ...
        'B_t2',            B_t2,              ...
        'ttm_1',           ttm_1,             ...
        'ttm_2',           ttm_2,             ...
        'rate_1',          rate_1,            ...
        'rate_2',          rate_2,            ...
        'F0_t1',           F0_t1,             ...
        'strike',          strike,             ...
        'dates_bootstrap',  dates,...
        'discounts_bootstrap', discounts, ...
        'spread', spread...
        );
end